.git
.github
.direnv
.go
.venv
.webkit-compat
bin
build-dir
coverage.out
dist
node_modules
packaging
release
result
site
test_data
tmp

frontend/dist
frontend/node_modules
internal/server/docs_site
internal/server/static
requirements/site

data
docs_site
resources

R scripts

*.7z
*.docx
*.exe
*.gguf
*.gob
*.gpkg
*.html
*.mbtiles
*.png
