.git
.github
.direnv
.go
.webkit-compat
bin
build-dir
coverage.out
dist
node_modules
release
result
site
tmp

frontend/dist
frontend/node_modules
internal/server/docs_site
internal/server/static
requirements/site

*.exe
*.gguf
*.gob
*.gpkg
*.mbtiles

data/*.csv
data/*.geoparquet
data/*.json
data/*.mbtiles
data/*.parquet
data/images
data/sites
